# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='naslov',
            field=models.CharField(max_length=100),
        ),
    ]
