# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=50)),
                ('datoteka', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
